package com.demo.web.daos;

import java.sql.SQLException;
import java.util.List;
import com.demo.web.models.Record;
import com.demo.web.models.RecordExample;

public interface RecordDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table record
     *
     * @ibatorgenerated Wed Dec 16 11:16:06 CST 2015
     */
    int countByExample(RecordExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table record
     *
     * @ibatorgenerated Wed Dec 16 11:16:06 CST 2015
     */
    int deleteByExample(RecordExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table record
     *
     * @ibatorgenerated Wed Dec 16 11:16:06 CST 2015
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table record
     *
     * @ibatorgenerated Wed Dec 16 11:16:06 CST 2015
     */
    void insert(Record record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table record
     *
     * @ibatorgenerated Wed Dec 16 11:16:06 CST 2015
     */
    void insertSelective(Record record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table record
     *
     * @ibatorgenerated Wed Dec 16 11:16:06 CST 2015
     */
    List selectByExample(RecordExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table record
     *
     * @ibatorgenerated Wed Dec 16 11:16:06 CST 2015
     */
    Record selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table record
     *
     * @ibatorgenerated Wed Dec 16 11:16:06 CST 2015
     */
    int updateByExampleSelective(Record record, RecordExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table record
     *
     * @ibatorgenerated Wed Dec 16 11:16:06 CST 2015
     */
    int updateByExample(Record record, RecordExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table record
     *
     * @ibatorgenerated Wed Dec 16 11:16:06 CST 2015
     */
    int updateByPrimaryKeySelective(Record record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table record
     *
     * @ibatorgenerated Wed Dec 16 11:16:06 CST 2015
     */
    int updateByPrimaryKey(Record record) throws SQLException;
}